[server]
ip_address = "localhost"

[security]
enable = true
timeout = 25

#[keystore]
#generate = false
#file = "letsencrypt.jks"
#password = "password"

[mongo]
enable = true
uri = "mongodb://localhost:27017"
db = "dev"
UserRepo = "users"
PasswordRepo = "store"

UserTestoRepo = "test"
TestRepo = "test2"
