name = "salt"

port = "8080"

[servers]

  # Einruecken (sowohl Tabs als auch Leerzeichen) ist erlaubt, aber nicht erforderlich
  [servers.alpha]
  ip = "10.0.0.1" # aaaaa
  dc = "eqdc10"

  [servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[clients]
data = [ ["gamma", "delta"], [1, 2] ]
ports = [ 8001, 8001, 8002 ]

